const data = {
    "data": [
        {
            "properties": {
                "screen": "AMOLED",
                "resolution": "Full HD + (1080 x 2220 Pixels)",
                "widescreen": 6.3,
                "touchglass": "Gorilla Glass toughened glass",
                "camera": "24 MP and 16 MP (2 cameras)",
                "film": "Movie FullHD 1080p @ 30fps , Shoot 4K 2160p @ 30fps movies",
                "operatingsystem": "Android 8.0 (Oreo)",
                "chipset": "(CPU maker)Qualcomm Snapdragon 660 8 core",
                "cpuspeed": "4 cores 2.2 GHz & 4 cores 1.8 GHz",
                "ram": "4GB",
                "internalmemory": "64 GB",
                "mobilenetwork": "3G, 4G LTE Cat 6",
                "sim": "2 Nano SIM",
                "batterycapacity": "3700 mAh",
                "discount": "20"
            },
            "_id": "5c500d910288e21748bb9d99",
            "brand": "NOKIA",
            "name": "Sam sung s6",
            "quantity": 888,
            "price": 99.9,
            "__v": 0
        },
        {
            "properties": {
                "screen": "AMOLED",
                "resolution": "Full HD + (1080 x 2220 Pixels)",
                "widescreen": 6.3,
                "touchglass": "Gorilla Glass toughened glass",
                "camera": "24 MP and 16 MP (2 cameras)",
                "film": "Movie FullHD 1080p @ 30fps , Shoot 4K 2160p @ 30fps movies",
                "operatingsystem": "Android 8.0 (Oreo)",
                "chipset": "(CPU maker)Qualcomm Snapdragon 660 8 core",
                "cpuspeed": "4 cores 2.2 GHz & 4 cores 1.8 GHz",
                "ram": "4GB",
                "internalmemory": "64 GB",
                "mobilenetwork": "3G, 4G LTE Cat 6",
                "sim": "2 Nano SIM",
                "batterycapacity": "3700 mAh",
                "discount": "20"
            },
            "_id": "5c500d930288e21748bb9d9a",
            "brand": "NOKIA",
            "name": "Sam sung s6",
            "quantity": 888,
            "price": 99.9,
            "__v": 0
        },
        {
            "properties": {
                "screen": "AMOLED",
                "resolution": "Full HD + (1080 x 2220 Pixels)",
                "widescreen": 6.3,
                "touchglass": "Gorilla Glass toughened glass",
                "camera": "24 MP and 16 MP (2 cameras)",
                "film": "Movie FullHD 1080p @ 30fps , Shoot 4K 2160p @ 30fps movies",
                "operatingsystem": "Android 8.0 (Oreo)",
                "chipset": "(CPU maker)Qualcomm Snapdragon 660 8 core",
                "cpuspeed": "4 cores 2.2 GHz & 4 cores 1.8 GHz",
                "ram": "4GB",
                "internalmemory": "64 GB",
                "mobilenetwork": "3G, 4G LTE Cat 6",
                "sim": "2 Nano SIM",
                "batterycapacity": "3700 mAh",
                "discount": "20"
            },
            "_id": "5c500d950288e21748bb9d9b",
            "brand": "NOKIA",
            "name": "Sam sung s6",
            "quantity": 888,
            "price": 99.9,
            "__v": 0
        },
        {
            "properties": {
                "screen": "AMOLED",
                "resolution": "Full HD + (1080 x 2220 Pixels)",
                "widescreen": 6.3,
                "touchglass": "Gorilla Glass toughened glass",
                "camera": "24 MP and 16 MP (2 cameras)",
                "film": "Movie FullHD 1080p @ 30fps , Shoot 4K 2160p @ 30fps movies",
                "operatingsystem": "Android 8.0 (Oreo)",
                "chipset": "(CPU maker)Qualcomm Snapdragon 660 8 core",
                "cpuspeed": "4 cores 2.2 GHz & 4 cores 1.8 GHz",
                "ram": "4GB",
                "internalmemory": "64 GB",
                "mobilenetwork": "3G, 4G LTE Cat 6",
                "sim": "2 Nano SIM",
                "batterycapacity": "3700 mAh",
                "discount": "20"
            },
            "_id": "5c500d960288e21748bb9d9c",
            "brand": "NOKIA",
            "name": "Sam sung s6",
            "quantity": 888,
            "price": 99.9,
            "__v": 0
        },
        {
            "properties": {
                "screen": "AMOLED",
                "resolution": "Full HD + (1080 x 2220 Pixels)",
                "widescreen": 6.3,
                "touchglass": "Gorilla Glass toughened glass",
                "camera": "24 MP and 16 MP (2 cameras)",
                "film": "Movie FullHD 1080p @ 30fps , Shoot 4K 2160p @ 30fps movies",
                "operatingsystem": "Android 8.0 (Oreo)",
                "chipset": "(CPU maker)Qualcomm Snapdragon 660 8 core",
                "cpuspeed": "4 cores 2.2 GHz & 4 cores 1.8 GHz",
                "ram": "4GB",
                "internalmemory": "64 GB",
                "mobilenetwork": "3G, 4G LTE Cat 6",
                "sim": "2 Nano SIM",
                "batterycapacity": "3700 mAh",
                "discount": "20"
            },
            "_id": "5c500d970288e21748bb9d9d",
            "brand": "NOKIA",
            "name": "Sam sung s6",
            "quantity": 888,
            "price": 99.9,
            "__v": 0
        },
        {
            "properties": {
                "screen": "AMOLED",
                "resolution": "Full HD + (1080 x 2220 Pixels)",
                "widescreen": 6.3,
                "touchglass": "Gorilla Glass toughened glass",
                "camera": "24 MP and 16 MP (2 cameras)",
                "film": "Movie FullHD 1080p @ 30fps , Shoot 4K 2160p @ 30fps movies",
                "operatingsystem": "Android 8.0 (Oreo)",
                "chipset": "(CPU maker)Qualcomm Snapdragon 660 8 core",
                "cpuspeed": "4 cores 2.2 GHz & 4 cores 1.8 GHz",
                "ram": "4GB",
                "internalmemory": "64 GB",
                "mobilenetwork": "3G, 4G LTE Cat 6",
                "sim": "2 Nano SIM",
                "batterycapacity": "3700 mAh",
                "discount": "20"
            },
            "_id": "5c500d980288e21748bb9d9f",
            "brand": "NOKIA",
            "name": "Sam sung s6",
            "quantity": 888,
            "price": 99.9,
            "__v": 0
        },
        {
            "properties": {
                "screen": "AMOLED",
                "resolution": "Full HD + (1080 x 2220 Pixels)",
                "widescreen": 6.3,
                "touchglass": "Gorilla Glass toughened glass",
                "camera": "24 MP and 16 MP (2 cameras)",
                "film": "Movie FullHD 1080p @ 30fps , Shoot 4K 2160p @ 30fps movies",
                "operatingsystem": "Android 8.0 (Oreo)",
                "chipset": "(CPU maker)Qualcomm Snapdragon 660 8 core",
                "cpuspeed": "4 cores 2.2 GHz & 4 cores 1.8 GHz",
                "ram": "4GB",
                "internalmemory": "64 GB",
                "mobilenetwork": "3G, 4G LTE Cat 6",
                "sim": "2 Nano SIM",
                "batterycapacity": "3700 mAh",
                "discount": "20"
            },
            "_id": "5c6399d68e9c9c00172f7fa5",
            "brand": "NOKIA",
            "name": "Sam sung s6",
            "quantity": 888,
            "price": 99.9,
            "__v": 0
        },
        {
            "properties": {
                "screen": "AMOLED",
                "resolution": "Full HD + (1080 x 2220 Pixels)",
                "widescreen": 6.3,
                "touchglass": "Gorilla Glass toughened glass",
                "camera": "24 MP and 16 MP (2 cameras)",
                "film": "Movie FullHD 1080p @ 30fps , Shoot 4K 2160p @ 30fps movies",
                "operatingsystem": "Android 8.0 (Oreo)",
                "chipset": "(CPU maker)Qualcomm Snapdragon 660 8 core",
                "cpuspeed": "4 cores 2.2 GHz & 4 cores 1.8 GHz",
                "ram": "4GB",
                "internalmemory": "64 GB",
                "mobilenetwork": "3G, 4G LTE Cat 6",
                "sim": "2 Nano SIM",
                "batterycapacity": "3700 mAh",
                "discount": "20"
            },
            "_id": "5c500d990288e21748bb9da0",
            "brand": "NOKIA",
            "name": "Sam sung s6",
            "quantity": 888,
            "price": 99.9,
            "__v": 0
        },
        {
            "properties": {
                "screen": "AMOLED",
                "resolution": "Full HD + (1080 x 2220 Pixels)",
                "widescreen": 6.3,
                "touchglass": "Gorilla Glass toughened glass",
                "camera": "24 MP and 16 MP (2 cameras)",
                "film": "Movie FullHD 1080p @ 30fps , Shoot 4K 2160p @ 30fps movies",
                "operatingsystem": "Android 8.0 (Oreo)",
                "chipset": "(CPU maker)Qualcomm Snapdragon 660 8 core",
                "cpuspeed": "4 cores 2.2 GHz & 4 cores 1.8 GHz",
                "ram": "4GB",
                "internalmemory": "64 GB",
                "mobilenetwork": "3G, 4G LTE Cat 6",
                "sim": "2 Nano SIM",
                "batterycapacity": "3700 mAh",
                "discount": "20"
            },
            "_id": "5c500d9a0288e21748bb9da1",
            "brand": "NOKIA",
            "name": "Sam sung s6",
            "quantity": 888,
            "price": 99.9,
            "__v": 0
        },
        {
            "properties": {
                "screen": "AMOLED",
                "resolution": "Full HD + (1080 x 2220 Pixels)",
                "widescreen": 6.3,
                "touchglass": "Gorilla Glass toughened glass",
                "camera": "24 MP and 16 MP (2 cameras)",
                "film": "Movie FullHD 1080p @ 30fps , Shoot 4K 2160p @ 30fps movies",
                "operatingsystem": "Android 8.0 (Oreo)",
                "chipset": "(CPU maker)Qualcomm Snapdragon 660 8 core",
                "cpuspeed": "4 cores 2.2 GHz & 4 cores 1.8 GHz",
                "ram": "4GB",
                "internalmemory": "64 GB",
                "mobilenetwork": "3G, 4G LTE Cat 6",
                "sim": "2 Nano SIM",
                "batterycapacity": "3700 mAh",
                "discount": "20"
            },
            "_id": "5c500d9b0288e21748bb9da2",
            "brand": "NOKIA",
            "name": "Sam sung s6",
            "quantity": 888,
            "price": 99.9,
            "__v": 0
        }
    ],
    "page": 0,
    "pages": 1.1
}
export default data